//! #704 surface audit — the internal task/thread admission-capacity vocabulary
//! must not appear anywhere in the public/generated surface.
//!
//! #704 removed the internal capacity concept: there is no per-operation task
//! admission, no per-session executor, and the error types
//! `ThreadUnavailable`/`ExecutorSaturated`/`WaiterSaturated`
//! /`RelayInformationWaitersSaturated` were deleted, along with any
//! `maxNativeTasks`/`nativeTaskCensus`/`awaitNativeTasksIdle` (and snake_case)
//! configuration/introspection surface. This test greps the repo's generated
//! API surface dumps and the hand-written SDK sources for those identifiers and
//! fails, printing every offending file:line, if any survive.
//!
//! Migration/removal prose is exempt: a line that documents the #704 removal
//! (contains `#704` or `removed`) is allowed to name the vanished identifiers.
//! The exemption is intentionally narrow — only those two markers.
//!
//! NOTE: `docs/surface/*` is regenerated by the surface tooling. If this test
//! fails ONLY on `docs/surface/*.txt` lines, the surface dumps are stale and
//! will pass once regenerated; a failure on a hand-written SDK source is a real
//! regression.

use std::fs;
use std::path::{Path, PathBuf};

/// Identifiers that must not survive in the public surface (#704).
const BANNED: &[&str] = &[
    "ThreadUnavailable",
    "ExecutorSaturated",
    "WaiterSaturated",
    "RelayInformationWaitersSaturated",
    "maxNativeTasks",
    "max_native_tasks",
    "nativeTaskCensus",
    "native_task_census",
    "awaitNativeTasksIdle",
    "await_native_tasks_idle",
];

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is `<repo>/crates/nmp-ffi`.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .canonicalize()
        .expect("repo root resolves from CARGO_MANIFEST_DIR")
}

/// A line is exempt if it is documenting the #704 removal.
fn is_exempt(line: &str) -> bool {
    line.contains("#704") || line.to_ascii_lowercase().contains("removed")
}

fn collect_source_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_source_files(&path, out);
        } else if path
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|e| matches!(e, "swift" | "kt"))
        {
            out.push(path);
        }
    }
}

fn scan_file(path: &Path, root: &Path, offenders: &mut Vec<String>) {
    let Ok(contents) = fs::read_to_string(path) else {
        return;
    };
    let display = path.strip_prefix(root).unwrap_or(path).display();
    for (i, line) in contents.lines().enumerate() {
        if is_exempt(line) {
            continue;
        }
        for token in BANNED {
            if line.contains(token) {
                offenders.push(format!("{display}:{}: [{token}] {}", i + 1, line.trim()));
            }
        }
    }
}

#[test]
fn public_surface_has_no_capacity_vocabulary() {
    let root = repo_root();

    // Generated API surface dumps (regenerated by the surface tooling).
    let mut files: Vec<PathBuf> = vec![
        root.join("docs/surface/nmp-facade.txt"),
        root.join("docs/surface/nmp-ffi-component.txt"),
    ];
    for surface in &files {
        assert!(
            surface.exists(),
            "expected surface dump missing: {}",
            surface.display()
        );
    }

    // Hand-written SDK sources.
    collect_source_files(&root.join("Packages/NMP/Sources/NMP"), &mut files);
    collect_source_files(
        &root.join("Packages/NMPKotlin/src/main/kotlin/com/nmp/sdk"),
        &mut files,
    );

    let mut offenders = Vec::new();
    for file in &files {
        scan_file(file, &root, &mut offenders);
    }

    // Partition so the report makes the stale-docs case obvious.
    let (surface_only, sdk): (Vec<_>, Vec<_>) = offenders
        .iter()
        .partition(|o| o.starts_with("docs/surface/"));

    if !offenders.is_empty() {
        eprintln!(
            "\n#704 surface audit found {} occurrence(s) of removed capacity vocabulary:",
            offenders.len()
        );
        for o in &offenders {
            eprintln!("  {o}");
        }
        if sdk.is_empty() {
            eprintln!(
                "\n(all offenders are in docs/surface/*.txt — stale generated dumps; \
                 they will disappear once the surface tooling regenerates them.)\n"
            );
        }
    }

    assert!(
        offenders.is_empty(),
        "public surface still names #704-removed capacity identifiers: {} in docs/surface, \
         {} in hand-written SDK sources (see stderr for file:line). SDK-source offenders are \
         real regressions; docs/surface-only offenders are stale until regenerated.",
        surface_only.len(),
        sdk.len()
    );
}
