// swift-tools-version:5.9
// M4 plan §2/§3: the Swift package boundary.
//
//   nmp_ffiFFI   -- binaryTarget -> NMP.xcframework (the compiled Rust
//                   core; regenerate via scripts/build-swift-xcframework.sh
//                   from the repo root -- NOT committed, see .gitignore).
//   NMPFFI       -- the uniffi-generated Swift bindings (Sources/NMPFFI/
//                   nmp_ffi.swift), also regenerated by the same script and
//                   NOT committed.
//   NMP          -- the hand-written ergonomic layer (Sources/NMP/), the
//                   ONLY target a consuming app imports. Holds zero engine
//                   concepts of its own -- AsyncSequence conformances,
//                   deinit-tied teardown, and @Observable sugar over NMPFFI.
//   NMPContent   -- optional pure semantic document parsing. It depends on
//                   generated parser values, not the NMP engine layer.
//   NMPUI        -- optional native SwiftUI primitives, controlled relay
//                   identity views, content renderer, and ready-made
//                   compositions over NMPContent.
//   NMPTests     -- XCTest target exercising NMP's public surface, including
//                   one bounded live-relay test (§ below).
//
// `swift build`/`swift test` do NOT work straight after a clean `git clone`
// -- `nmp_ffiFFI`'s binaryTarget and NMPFFI's generated source must be built
// once first. See README.md in this directory for the one-command fix
// (#18); CI proves that exact path on every push via the `swift-package`
// job in .github/workflows/ci.yml.
import PackageDescription

let package = Package(
    name: "NMP",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(name: "NMP", targets: ["NMP"]),
        .library(name: "NMPContent", targets: ["NMPContent"]),
        .library(name: "NMPUI", targets: ["NMPUI"]),
    ],
    targets: [
        .binaryTarget(
            name: "nmp_ffiFFI",
            path: "NMP.xcframework"
        ),
        .target(
            name: "NMPFFI",
            dependencies: ["nmp_ffiFFI"],
            linkerSettings: [
                .linkedFramework(
                    "SystemConfiguration",
                    .when(platforms: [.iOS, .macOS])
                ),
            ]
        ),
        .target(
            name: "NMP",
            dependencies: ["NMPFFI"]
        ),
        .target(
            name: "NMPContent",
            dependencies: ["NMPFFI"]
        ),
        .target(
            name: "NMPUI",
            dependencies: ["NMP", "NMPContent"]
        ),
        .testTarget(
            name: "NMPTests",
            dependencies: ["NMP"]
        ),
        .testTarget(
            name: "NMPContentTests",
            dependencies: ["NMPContent"]
        ),
        .testTarget(
            name: "NMPUITests",
            dependencies: ["NMP", "NMPUI"]
        ),
    ]
)
