// swift-tools-version:5.9
// M4 plan §2/§3: the Swift package boundary.
//
//   nmp_ffiFFI   -- binaryTarget -> NMP.xcframework (the compiled Rust
//                   core; regenerate via scripts/build-swift-xcframework.sh
//                   from the repo root -- NOT committed, see .gitignore).
//   NMPFFI       -- the uniffi-generated Swift bindings (Sources/NMPFFI/
//                   nmp_ffi.swift), also regenerated by the same script and
//                   NOT committed.
//   NMP          -- the hand-written ergonomic layer (Sources/NMP/), the
//                   ONLY target a consuming app imports. Holds zero engine
//                   concepts of its own -- AsyncSequence conformances,
//                   deinit-tied teardown, and @Observable sugar over NMPFFI.
//   NMPTests     -- XCTest target exercising NMP's public surface, including
//                   one bounded live-relay test (§ below).
import PackageDescription

let package = Package(
    name: "NMP",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(name: "NMP", targets: ["NMP"]),
    ],
    targets: [
        .binaryTarget(
            name: "nmp_ffiFFI",
            path: "NMP.xcframework"
        ),
        .target(
            name: "NMPFFI",
            dependencies: ["nmp_ffiFFI"]
        ),
        .target(
            name: "NMP",
            dependencies: ["NMPFFI"]
        ),
        .testTarget(
            name: "NMPTests",
            dependencies: ["NMP"]
        ),
    ]
)
