// #40: the Kotlin/Flow falsifier build. Mirrors Packages/NMP/Package.swift's
// three-layer shape:
//
//   (native lib)  -- crates/nmp-ffi's cdylib, built + copied into
//                    src/main/resources/<jna-prefix>/ by
//                    scripts/build-kotlin-jvm.sh. NOT committed (.gitignore).
//   uniffi.nmp_ffi -- the uniffi-bindgen-generated Kotlin bindings
//                    (src/main/kotlin/uniffi/nmp_ffi/), also generated by
//                    the same script, also NOT committed.
//   com.nmp.sdk   -- the hand-written ergonomic layer (this module's own
//                    src/main/kotlin/com/nmp/sdk/), the only package a
//                    consuming app imports. Mirrors NMP's AsyncSequence
//                    bridge with a `Flow` bridge instead (see Query.kt).
//
// `./gradlew build`/`./gradlew test` do NOT work straight after a clean
// clone -- the generated bindings + native lib must be built once first via
// scripts/build-kotlin-jvm.sh from the repo root. See README.md in this
// directory; CI proves that exact path on every push via the
// `kotlin-package` job in .github/workflows/ci.yml (mirroring the
// `swift-package` job).
import java.time.Duration

plugins {
    kotlin("jvm") version "2.0.21"
}

group = "com.nmp"

repositories {
    mavenCentral()
}

dependencies {
    // UniFFI's Kotlin bindings load the native library through JNA
    // (Native.load) -- there is no Kotlin/JVM equivalent of Swift's
    // binaryTarget, so this is the JVM falsifier's own added dependency
    // (Rust/Swift never needed one).
    implementation("net.java.dev.jna:jna:5.14.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")

    testImplementation(kotlin("test"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testImplementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

kotlin {
    jvmToolchain(17)
}

tasks.test {
    useJUnitPlatform()
    systemProperty(
        "nmp.referenceFixturePath",
        rootProject.projectDir.resolve("../../fixtures/reference-plans.json").canonicalPath,
    )
    // Live-relay test only, same discipline as LiveRelayTests.swift -- every
    // wait inside the test itself is already bounded (~30s), this is just a
    // hard backstop so a genuinely hung JVM/network call can't wedge CI.
    timeout.set(Duration.ofMinutes(3))
    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
    }
}
