#!/usr/bin/env bash
set -euo pipefail

# PROGRAM_ROOT is where this program lives and where every tool it runs comes
# from; ROOT is the tree being regenerated. In CI the two differ: the gate
# extracts this program from the base commit and points it at the proposed
# head, and resolving a tool from the head would run the head's own tooling
# under base trust (#1186).
PROGRAM_ROOT=$(cd "$(dirname "$0")/.." && pwd)
ROOT=${SURFACE_ROOT:-$(git rev-parse --show-toplevel)}
HEAD_REF=${SURFACE_HEAD_REF:-HEAD}
OUTPUT_DIR="$ROOT/docs/surface"

if [[ ${1:-} == "--output-dir" ]]; then
  [[ $# -eq 2 ]] || { echo "usage: $0 [--output-dir DIR]" >&2; exit 2; }
  OUTPUT_DIR=$2
elif [[ $# -ne 0 ]]; then
  echo "usage: $0 [--output-dir DIR]" >&2
  exit 2
fi

# shellcheck disable=SC1091
source "$PROGRAM_ROOT/tools/surface-toolchain.env"
PUBLIC_API_VERSION=$CARGO_PUBLIC_API_VERSION
COMPONENT_TOOL_DIR="$PROGRAM_ROOT/tools/component-interface-snapshot"
CATALOG_TOOL_DIR="$PROGRAM_ROOT/tools/surface-component-catalog"
RUST_FACADE_TOOL_DIR="$PROGRAM_ROOT/tools/rust-facade-snapshot"

command -v cargo-public-api >/dev/null || {
  echo "cargo-public-api is required; install with:" >&2
  echo "  cargo install --locked cargo-public-api@$PUBLIC_API_VERSION" >&2
  exit 1
}
[[ $(cargo-public-api --version) == "cargo-public-api $PUBLIC_API_VERSION" ]] || {
  echo "cargo-public-api $PUBLIC_API_VERSION is required" >&2
  exit 1
}

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$OUTPUT_DIR"
cd "$ROOT"
# Rustdoc writes one shared `<crate>.json` path even when Cargo fingerprints
# distinct feature sets. Keep the complete governed surface below its own
# stable namespace so a preceding default-feature build cannot make an
# all-feature regeneration silently reuse a truncated document.
BUILD_TARGET_ROOT=${SURFACE_BUILD_TARGET_DIR:-$TMP/build-target}
BUILD_TARGET="$BUILD_TARGET_ROOT/complete-feature-surface"
mkdir -p "$BUILD_TARGET"

CATALOG_BIN=${SURFACE_CATALOG_BIN:-}
if [[ -z "$CATALOG_BIN" ]]; then
  CATALOG_TARGET=${SURFACE_CATALOG_TARGET_DIR:-$TMP/catalog-tool-target}
  cargo "+$SURFACE_RUST_TOOLCHAIN" build --quiet --locked \
    --manifest-path "$CATALOG_TOOL_DIR/Cargo.toml" \
    --target-dir "$CATALOG_TARGET"
  CATALOG_BIN="$CATALOG_TARGET/debug/nmp-surface-component-catalog"
fi
[[ -x "$CATALOG_BIN" ]] || {
  echo "surface component catalog tool is unavailable: $CATALOG_BIN" >&2
  exit 1
}
"$CATALOG_BIN" validate "$ROOT" "$HEAD_REF" >/dev/null

{
  echo "# Generated by scripts/regenerate-surface-snapshots.sh"
  echo "# cargo-public-api: $PUBLIC_API_VERSION"
  echo "# rust toolchain: $SURFACE_RUST_TOOLCHAIN"
  echo "# crate: nmp"
  CARGO_TARGET_DIR="$BUILD_TARGET/public-api" \
    cargo "+$SURFACE_RUST_TOOLCHAIN" public-api -p nmp --all-features --simplified
  echo
  (
    cd "$RUST_FACADE_TOOL_DIR"
    CARGO_TARGET_DIR="$BUILD_TARGET/rust-facade-tool" \
      cargo "+$SURFACE_RUST_TOOLCHAIN" run --quiet --locked \
        --manifest-path Cargo.toml -- \
        "$ROOT" "$SURFACE_RUST_TOOLCHAIN" "$BUILD_TARGET/facade-rustdoc"
  )
} > "$TMP/nmp-facade.txt"

# The complete feature-selected facade has dozens of explicit roots, not
# arbitrary dependency method inventories. These generous ceilings catch
# accidental recursive impl expansion while leaving substantial room for
# intentional surface growth across the full all-feature governance build.
RUST_FACADE_MAX_LINES=60000
RUST_FACADE_MAX_BYTES=12000000
RUST_FACADE_LINES=$(wc -l < "$TMP/nmp-facade.txt")
RUST_FACADE_BYTES=$(wc -c < "$TMP/nmp-facade.txt")
(( RUST_FACADE_LINES <= RUST_FACADE_MAX_LINES )) || {
  echo "Rust facade snapshot exceeds $RUST_FACADE_MAX_LINES lines: $RUST_FACADE_LINES" >&2
  exit 1
}
(( RUST_FACADE_BYTES <= RUST_FACADE_MAX_BYTES )) || {
  echo "Rust facade snapshot exceeds $RUST_FACADE_MAX_BYTES bytes: $RUST_FACADE_BYTES" >&2
  exit 1
}
if grep -Eq 'CfgTrace|CfgAttrTrace|#\[attr = Inline|/Users/|/home/|/private/var/|\.cargo/registry' "$TMP/nmp-facade.txt"; then
  echo "Rust facade snapshot contains compiler trace noise or an absolute source path" >&2
  exit 1
fi
if grep -Eq '"impls"|"blanket_impl"|"id": [0-9]|local-item:' "$TMP/nmp-facade.txt"; then
  echo "Rust facade snapshot contains an impl inventory or unstable rustdoc id" >&2
  exit 1
fi

"$CATALOG_BIN" active-rows "$ROOT" "$HEAD_REF" > "$TMP/active-rows"
mkdir -p "$TMP/rows"
: > "$TMP/allowed-namespaces"
row_count=0
exec 3< "$TMP/active-rows"
while IFS= read -r -d '' key <&3; do
  IFS= read -r -d '' owner <&3
  IFS= read -r -d '' namespace <&3
  IFS= read -r -d '' package <&3
  IFS= read -r -d '' manifest <&3
  IFS= read -r -d '' library_stem <&3
  IFS= read -r -d '' snapshot <&3
  row_count=$((row_count + 1))
  row_file=$(printf '%s/%06d' "$TMP/rows" "$row_count")
  printf '%s\0%s\0%s\0%s\0%s\0%s\0%s\0' \
    "$key" "$owner" "$namespace" "$package" "$manifest" "$library_stem" "$snapshot" \
    > "$row_file"
  printf '%s\0' "$namespace" >> "$TMP/allowed-namespaces"
done
exec 3<&-
(( row_count > 0 )) || {
  echo "component catalog returned no active rows" >&2
  exit 1
}

case "${SURFACE_COMPONENT_ORDER:-catalog}" in
  catalog)
    cp "$TMP/active-rows" "$TMP/ordered-active-rows"
    ;;
  reverse)
    : > "$TMP/ordered-active-rows"
    row_index=$row_count
    while (( row_index > 0 )); do
      row_file=$(printf '%s/%06d' "$TMP/rows" "$row_index")
      cat "$row_file" >> "$TMP/ordered-active-rows"
      row_index=$((row_index - 1))
    done
    ;;
  *)
    echo "SURFACE_COMPONENT_ORDER must be catalog or reverse" >&2
    exit 2
    ;;
esac

exec 3< "$TMP/ordered-active-rows"
while IFS= read -r -d '' key <&3; do
  IFS= read -r -d '' owner <&3
  IFS= read -r -d '' namespace <&3
  IFS= read -r -d '' package <&3
  IFS= read -r -d '' manifest <&3
  IFS= read -r -d '' library_stem <&3
  IFS= read -r -d '' snapshot <&3

  # Different artifact owners never share Cargo output state. Co-located
  # namespaces still reuse their one owner's exact build.
  owner_target="$BUILD_TARGET/component-owners/$owner"
  owner_marker="$TMP/owners/$owner"
  mkdir -p "$TMP/owners"
  if [[ ! -f "$owner_marker" ]]; then
    # Governance snapshots describe the owner's complete supported surface,
    # independent of any one app manifest. App artifacts use the native
    # prepare command's exact `--no-default-features --features ...` build.
    CARGO_TARGET_DIR="$owner_target" \
      cargo "+$SURFACE_RUST_TOOLCHAIN" build --quiet --locked \
        --manifest-path "$ROOT/$manifest" \
        --package "$package" \
        --all-features \
        --lib
    case "$(uname -s)" in
      Darwin) library="$owner_target/debug/lib$library_stem.dylib" ;;
      Linux) library="$owner_target/debug/lib$library_stem.so" ;;
      MINGW*|MSYS*|CYGWIN*) library="$owner_target/debug/$library_stem.dll" ;;
      *) echo "unsupported host for UniFFI metadata extraction" >&2; exit 1 ;;
    esac
    [[ -f "$library" ]] || {
      echo "built component library not found: $library" >&2
      exit 1
    }
    printf '%s\n' "$library" > "$owner_marker"
  fi
  library=$(<"$owner_marker")

  generated="$TMP/generated/$snapshot"
  mkdir -p "$(dirname "$generated")"
  {
    echo "# Generated by scripts/regenerate-surface-snapshots.sh"
    echo "# UniFFI: $UNIFFI_VERSION"
    echo "# rust toolchain: $SURFACE_RUST_TOOLCHAIN"
    (
      cd "$COMPONENT_TOOL_DIR"
      CARGO_TARGET_DIR="$BUILD_TARGET/component-tool" \
        cargo "+$SURFACE_RUST_TOOLCHAIN" run --quiet --locked \
          --manifest-path Cargo.toml -- \
          "$library" "$key" "$namespace" "$TMP/allowed-namespaces"
    )
  } > "$generated"

  lines=$(wc -l < "$generated" | tr -d ' ')
  bytes=$(wc -c < "$generated" | tr -d ' ')
  (( lines <= 20000 )) || {
    echo "$key component snapshot exceeds 20000 lines: $lines" >&2
    exit 1
  }
  (( bytes <= 2000000 )) || {
    echo "$key component snapshot exceeds 2000000 bytes: $bytes" >&2
    exit 1
  }
  if grep -Eq 'CfgTrace|CfgAttrTrace|#\[attr = Inline|/Users/|/home/|/private/var/|\.cargo/registry' "$generated"; then
    echo "$key component snapshot contains compiler noise or an absolute path" >&2
    exit 1
  fi
done
exec 3<&-

install -m 0644 "$TMP/nmp-facade.txt" "$OUTPUT_DIR/nmp-facade.txt"
while IFS= read -r -d '' key; do
  IFS= read -r -d '' _owner
  IFS= read -r -d '' _namespace
  IFS= read -r -d '' _package
  IFS= read -r -d '' _manifest
  IFS= read -r -d '' _library_stem
  IFS= read -r -d '' snapshot
  mkdir -p "$(dirname "$OUTPUT_DIR/${snapshot#docs/surface/}")"
  install -m 0644 "$TMP/generated/$snapshot" "$OUTPUT_DIR/${snapshot#docs/surface/}"
done < "$TMP/active-rows"
