#!/usr/bin/env bash
set -euo pipefail

ROOT=$(git rev-parse --show-toplevel)
OUTPUT_DIR="$ROOT/docs/surface"

if [[ ${1:-} == "--output-dir" ]]; then
  [[ $# -eq 2 ]] || { echo "usage: $0 [--output-dir DIR]" >&2; exit 2; }
  OUTPUT_DIR=$2
elif [[ $# -ne 0 ]]; then
  echo "usage: $0 [--output-dir DIR]" >&2
  exit 2
fi

# shellcheck disable=SC1091
source "${SURFACE_TOOLCHAIN_ENV:-$ROOT/tools/surface-toolchain.env}"
PUBLIC_API_VERSION=$CARGO_PUBLIC_API_VERSION
COMPONENT_TOOL_DIR=${SURFACE_COMPONENT_TOOL_DIR:-$ROOT/tools/component-interface-snapshot}
RUST_FACADE_TOOL_DIR=${SURFACE_RUST_FACADE_TOOL_DIR:-$ROOT/tools/rust-facade-snapshot}

command -v cargo-public-api >/dev/null || {
  echo "cargo-public-api is required; install with:" >&2
  echo "  cargo install --locked cargo-public-api@$PUBLIC_API_VERSION" >&2
  exit 1
}
[[ $(cargo-public-api --version) == "cargo-public-api $PUBLIC_API_VERSION" ]] || {
  echo "cargo-public-api $PUBLIC_API_VERSION is required" >&2
  exit 1
}

mkdir -p "$OUTPUT_DIR"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

cd "$ROOT"

{
  echo "# Generated by scripts/regenerate-surface-snapshots.sh"
  echo "# cargo-public-api: $PUBLIC_API_VERSION"
  echo "# rust toolchain: $SURFACE_RUST_TOOLCHAIN"
  echo "# crate: nmp"
  cargo "+$SURFACE_RUST_TOOLCHAIN" public-api -p nmp --simplified
  echo
  (
    cd "$RUST_FACADE_TOOL_DIR"
    CARGO_TARGET_DIR="$TMP/rust-facade-tool-target" \
      cargo "+$SURFACE_RUST_TOOLCHAIN" run --quiet --locked \
        --manifest-path Cargo.toml -- \
        "$ROOT" "$SURFACE_RUST_TOOLCHAIN" "$TMP/facade-rustdoc-target"
  )
} > "$TMP/nmp-facade.txt"

# The supported facade has dozens of explicit roots, not arbitrary dependency
# method inventories. These generous ceilings catch accidental recursive impl
# expansion while leaving substantial room for intentional surface growth.
# 2026-07-16 (#8 Wave 2, PR #541): raised 30000 -> 31000 for the NIP-42
# auth-diagnostics facade surface (AuthDiagnosticsSnapshot / AuthDiagnosticsPhase
# / AuthPhase variants / DiagnosticsSnapshot.auth_sessions), which is
# adversarially-reviewed intended growth (+~399 lines, no over-exposure).
RUST_FACADE_MAX_LINES=31000
RUST_FACADE_MAX_BYTES=8000000
RUST_FACADE_LINES=$(wc -l < "$TMP/nmp-facade.txt")
RUST_FACADE_BYTES=$(wc -c < "$TMP/nmp-facade.txt")
(( RUST_FACADE_LINES <= RUST_FACADE_MAX_LINES )) || {
  echo "Rust facade snapshot exceeds $RUST_FACADE_MAX_LINES lines: $RUST_FACADE_LINES" >&2
  exit 1
}
(( RUST_FACADE_BYTES <= RUST_FACADE_MAX_BYTES )) || {
  echo "Rust facade snapshot exceeds $RUST_FACADE_MAX_BYTES bytes: $RUST_FACADE_BYTES" >&2
  exit 1
}
if grep -Eq 'CfgTrace|CfgAttrTrace|#\[attr = Inline|/Users/|/home/|/private/var/|\.cargo/registry' "$TMP/nmp-facade.txt"; then
  echo "Rust facade snapshot contains compiler trace noise or an absolute source path" >&2
  exit 1
fi
if grep -Eq '"impls"|"blanket_impl"|"id": [0-9]|local-item:' "$TMP/nmp-facade.txt"; then
  echo "Rust facade snapshot contains an impl inventory or unstable rustdoc id" >&2
  exit 1
fi

cargo "+$SURFACE_RUST_TOOLCHAIN" build --locked -p nmp-ffi --lib >/dev/null
TARGET_DIR=$(cargo "+$SURFACE_RUST_TOOLCHAIN" metadata --locked --no-deps --format-version 1 | sed -n 's/.*"target_directory":"\([^"]*\)".*/\1/p')
case "$(uname -s)" in
  Darwin) LIB="$TARGET_DIR/debug/libnmp_ffi.dylib" ;;
  Linux) LIB="$TARGET_DIR/debug/libnmp_ffi.so" ;;
  MINGW*|MSYS*|CYGWIN*) LIB="$TARGET_DIR/debug/nmp_ffi.dll" ;;
  *) echo "unsupported host for UniFFI metadata extraction" >&2; exit 1 ;;
esac
[[ -f "$LIB" ]] || { echo "built nmp-ffi native library not found: $LIB" >&2; exit 1; }

{
  echo "# Generated by scripts/regenerate-surface-snapshots.sh"
  echo "# UniFFI: $UNIFFI_VERSION"
  echo "# rust toolchain: $SURFACE_RUST_TOOLCHAIN"
  (
    cd "$COMPONENT_TOOL_DIR"
    CARGO_TARGET_DIR="$TMP/component-tool-target" \
      cargo "+$SURFACE_RUST_TOOLCHAIN" run --quiet --locked \
        --manifest-path Cargo.toml -- "$LIB"
  )
} > "$TMP/nmp-ffi-component.txt"

install -m 0644 "$TMP/nmp-facade.txt" "$OUTPUT_DIR/nmp-facade.txt"
install -m 0644 "$TMP/nmp-ffi-component.txt" "$OUTPUT_DIR/nmp-ffi-component.txt"
